version: "3.7"
services:

  app_test:
    build: ./app
    command: "pipenv run ptw"
    volumes:
      - ./app:/app:delegated
    depends_on:
      - database
    tty: true
    stdin_open: true
    environment:
      TEST_VAR: test_var

  app:
      build: ./app
      command: "uvicorn src.main:app --host=0.0.0.0 --port=8000 --reload"
      ports:
        - "8000:8000"
      volumes:
        - ./app:/app:delegated
      depends_on:
        - database
      tty: true
      stdin_open: true
      environment:
        TEST_VAR: test_var

  database:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5000:5432"
    #volumes:
    #  - "db_data:/var/lib/postgresql/data"

#volumes:
#  db_data: null
