import os
import hmac

def authenticate_webhook_request(logger, x_hub_signature, payload):
    """
    Authenticates the incoming request to ensure that it is arriving from Whatsapp API

    Inputs:
        - logger: logger object
        - x_hub_signature: str x-hub-signature header value on the incoming request
        - payload: bytes body of request

    Reference: https://developers.facebook.com/docs/graph-api/webhooks/getting-started/#:~:text=int-,Validating%20Payloads,-We%20sign%20all

    NOTE:
        - The "app secret" can be obtained via the Meta Dashboard under "Settings" -> "Basic" -> "App Secret"
        - This is NOT the token that you set when configuring the webhook via the get request, but is
          generated by Facebook, but this can be reset via the "Reset" button next to the field
    """
    hashed = hmac.new(os.environ['WEBHOOK_SECRET'].encode(), payload, 'sha1')
    test_signature = hashed.hexdigest()

    if test_signature != x_hub_signature[4:]:
        logger.debug(f'UNAUTHORIZED incoming request: {payload}')
        return False

    return True